#config.yaml

## Choose between train_style0, train_style1, train_style2 or train_allstyles
TRAIN_STYLE_PATHS:
  -
      train_style0:  "/dtu/datasets1/02514/isic/train_style0"

  -
    train_style1:  "/dtu/datasets1/02514/isic/train_style1"

  -
    train_style2:  "/dtu/datasets1/02514/isic/train_style2"

  -
    train_allstyles:  "/dtu/datasets1/02514/isic/train_allstyles"

TEST_STYLE_PATH: "/dtu/datasets1/02514/isic/test_style0"

N_WORKERS: 4

IMG_SIZE: [240, 160]
ITER: 5

PIN_MEMORY: True

BEST_MODEL_PATH: "checkpoints/best_model.pth"
CHECKPOINT_PATH: "checkpoints/"