#config.yaml

EPOCHS: 20
BATCH_SIZE: 32
LEARNING_RATE: 1e-6

N_WORKERS: 4

BEST_MODEL_PATH: "checkpoints/best_model.pth"
CHECKPOINT_PATH: "checkpoints/"
DATASET_PATH: "/dtu/datasets1/02514/isic/"
## Choose between train_style0, train_style1, train_style2 or train_allstyles
TRAIN_STYLE: "train_style2"
TEST_SET: "test_style0"
IMG_SIZE: [224, 224]
ITER: 5
## Choose between FCN, UNet, UNet++
ARCHITECTURE: "grad_cam"

PIN_MEMORY: True